# Ana orchestration dosyası
# NODE_ENV ile production ve development ortamlarını destekler

x-common-variables: &common-variables
  NODE_ENV: ${NODE_ENV:-production}

services:
  # Frontend servisi
  frontend-prod:
    extends:
      file: ./frontend/frontend-compose.yml
      service: frontend-prod
    environment:
      <<: *common-variables
    profiles:
      - prod 

  # Development için ek servisler
  frontend-dev:
    extends:
      file: ./frontend/frontend-compose.yml
      service: frontend-dev
    environment:
      <<: *common-variables
      NODE_ENV: development
    profiles:
      - dev 

  # Backend servisi  
  backend-prod:
    extends:
      file: ./backend/backend-compose.yml
      service: backend-prod
    environment:
      <<: *common-variables
    profiles:
      - prod 

  backend-dev:
    extends:
      file: ./backend/backend-compose.yml
      service: backend-dev
    environment:
      <<: *common-variables
      NODE_ENV: development
    profiles:
      - dev 

# Ortak network
networks:
  app-network:
    driver: bridge
  dev-network:
    driver: bridge

# Volumes tanımlaması
volumes:
  redis_data:
