name: Frontend - Backend > Test & Merge

on:
  pull_request:
    branches:
      - main

jobs:
  # 1. Adım: Değişiklikleri Tespit Etme İşi ("Hangi Servis Güncellendi?")
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      # İhtiyaca göre diğer servisleri ekleyebilirsiniz: nginx, redis etc.
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changed services
        uses: dorny/paths-filter@v3
        id: filter # Bu adıma bir ID veriyoruz ki çıktılarına erişebilelim
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  # 2. Adım: Backend için Test, Build ve Deploy İşi
  test-backend:
    needs: changes # Bu işin çalışması için 'changes' işinin bitmesi gerekir
    if: needs.changes.outputs.backend == 'true' # Sadece backend dosyaları değiştiyse çalışır!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Backend Test
        run: |
          cd ./backend
          npm ci
          npm run test
  merge-backend:
    needs: test-backend
    runs-on: ubuntu-latest
    permissions: write-all
    
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Merge Backend Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr merge --auto --merge "$PR_URL" 

  # 3. Adım: Frontend için Test, Build ve Deploy İşi
  test-frontend:
    needs: changes # Bu işin çalışması için 'changes' işinin bitmesi gerekir
    if: needs.changes.outputs.frontend == 'true' # Sadece frontend dosyaları değiştiyse çalışır!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Frontend Test
        run: |
          cd ./frontend
          npm ci
          npm run test
  merge-frontend:
    needs: test-frontend
    runs-on: ubuntu-latest
    permissions: write-all

    if: github.event_name == 'pull_request'
    
    steps:
      - name: Merge Frontend Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr merge --auto --merge "$PR_URL"
